name = "Nexus Beyond"
author = "Lightning323"
version = "5.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53010fdecb5b7c4a173cb271d0bd15ab67163a26173693bc94be6056fd73ee65"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
