#KubeJS Common Properties
#Tue Sep 17 07:31:05 MDT 2024
matchJsonRecipes=true
allowAsyncStreams=true
announceReload=true
startupErrorGUI=true
serverOnly=false
hideServerScriptErrors=false
saveDevPropertiesInConfig=false
packmode=
ignoreCustomUniqueRecipeIds=false
creativeModeTabIcon=kubejs\:pyrotide_shard
startupErrorReportUrl=
