#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Mon Dec 15 15:31:43 MST 2025
farmersdelight=true
a=false
create=true
quark=true
mcwroofs=true
another_furniture=true
mcwdoors=true
mcwtrpdoors=true
