#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Feb 13 19:39:38 GMT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=Sildur's Vibrant Shaders v1.51 Lite.zip
enableShaders=false
