#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Feb 15 23:05:40 MST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=Sildur's Vibrant Shaders v1.51 Lite.zip
enableShaders=false
